import { localized as l, type ApiEndpoint } from './apiCatalogTypes'

export const iCloudEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/icloud/accounts', group: 'icloud', auth: 'authenticated',
    title: l('列出 iCloud 账户', 'List iCloud accounts'),
    description: l('返回当前用户连接的 iCloud 账户，不解密或返回凭据。', 'Return the current user’s connected iCloud accounts without decrypting or returning credentials.'),
    request: 'No parameters', response: '200 · { accounts }',
  },
  {
    method: 'POST', path: '/api/icloud/accounts', group: 'icloud', auth: 'authenticated',
    title: l('连接 iCloud 账户', 'Connect an iCloud account'),
    description: l('保存加密 Cookie、选择区域并验证 Apple 账户和隐藏地址。', 'Encrypt cookies, select the region, and validate the Apple account and aliases.'),
    request: 'JSON · name, cookies, host=icloud.com|icloud.com.cn', response: '201 · { account }',
    exampleBody: { name: 'My iCloud', cookies: { X_APPLE_WEB_KB: 'cookie-value' }, host: 'icloud.com' },
    notes: [l('Cookie 属于高敏感凭据，只应提交给自己的 OmniMail 实例。', 'Cookies are highly sensitive credentials and should only be sent to your own OmniMail instance.')],
  },
  {
    method: 'DELETE', path: '/api/icloud/accounts/:id', group: 'icloud', auth: 'authenticated',
    title: l('删除 iCloud 账户', 'Delete an iCloud account'),
    description: l('删除当前用户的加密 Cookie、应用专用密码和账户记录。', 'Delete the current user’s encrypted cookies, app password, and account record.'),
    request: 'Path · id', response: '200 · { ok: true }',
  },
  {
    method: 'PUT', path: '/api/icloud/accounts/:id/cookies', group: 'icloud', auth: 'authenticated',
    title: l('更新 iCloud Cookie', 'Update iCloud cookies'),
    description: l('覆盖并重新验证账户 Cookie，同时刷新别名统计。', 'Replace and revalidate account cookies, then refresh alias statistics.'),
    request: 'Path · id; JSON · cookies', response: '200 · { account }',
    exampleBody: { cookies: { X_APPLE_WEB_KB: 'new-cookie-value' } },
  },
  {
    method: 'PUT', path: '/api/icloud/accounts/:id/app-password', group: 'icloud', auth: 'authenticated',
    title: l('设置 iCloud 应用专用密码', 'Set an iCloud app-specific password'),
    description: l('验证 IMAP 登录后加密保存 iCloud 邮箱和应用专用密码。', 'Validate IMAP login, then encrypt the iCloud email and app-specific password.'),
    request: 'Path · id; JSON · icloudEmail, appPassword', response: '200 · { ok: true, icloudEmail }',
    exampleBody: { icloudEmail: 'owner@icloud.com', appPassword: 'xxxx-xxxx-xxxx-xxxx' },
  },
  {
    method: 'GET', path: '/api/icloud/aliases', group: 'icloud', auth: 'authenticated',
    title: l('同步隐藏邮箱地址', 'Sync Hide My Email aliases'),
    description: l('从 Apple 读取指定账户的全部隐藏邮箱地址并刷新 Cookie。', 'Read all Hide My Email aliases for an account from Apple and refresh cookies.'),
    request: 'Query · accountId', response: '200 · { aliases }',
    examplePath: '/api/icloud/aliases?accountId=icloud_account_id',
  },
  {
    method: 'POST', path: '/api/icloud/aliases', group: 'icloud', auth: 'authenticated',
    title: l('创建隐藏邮箱地址', 'Create a Hide My Email alias'),
    description: l('在指定 iCloud 账户中创建带标签的隐藏地址。', 'Create a labeled Hide My Email alias in the selected iCloud account.'),
    request: 'JSON · accountId, label?', response: '201 · { alias }',
    exampleBody: { accountId: 'icloud_account_id', label: 'Shopping' },
  },
  {
    method: 'PATCH', path: '/api/icloud/aliases/:anonymousId', group: 'icloud', auth: 'authenticated',
    title: l('停用或恢复隐藏地址', 'Deactivate or reactivate an alias'),
    description: l('对指定 Apple anonymousId 执行停用或恢复。', 'Deactivate or reactivate the selected Apple anonymousId.'),
    request: 'Path · anonymousId; JSON · accountId, action=deactivate|reactivate', response: '200 · { ok: true, action }',
    exampleBody: { accountId: 'icloud_account_id', action: 'deactivate' },
  },
  {
    method: 'DELETE', path: '/api/icloud/aliases/:anonymousId', group: 'icloud', auth: 'authenticated',
    title: l('永久删除隐藏地址', 'Permanently delete an alias'),
    description: l('从 Apple 永久删除指定隐藏地址并刷新账户统计。', 'Permanently delete the alias from Apple and refresh account statistics.'),
    request: 'Path · anonymousId; JSON · accountId', response: '200 · { ok: true }',
    exampleBody: { accountId: 'icloud_account_id' },
  },
  {
    method: 'GET', path: '/api/icloud/inbox', group: 'icloud', auth: 'authenticated',
    title: l('读取 iCloud 最近来信', 'List recent iCloud mail'),
    description: l('使用应用专用密码通过 IMAP 按需读取最近邮件摘要。', 'Use the app-specific password to read recent IMAP message summaries on demand.'),
    request: 'Query · accountId, alias?, limit=1..50?, days=0..365?', response: '200 · { messages, method=imap|web }',
    examplePath: '/api/icloud/inbox?accountId=icloud_account_id&limit=20&days=7',
  },
  {
    method: 'GET', path: '/api/icloud/inbox/:uid', group: 'icloud', auth: 'authenticated',
    title: l('读取 iCloud 邮件正文', 'Read an iCloud message'),
    description: l('通过 IMAP UID 读取完整正文和附件元数据。', 'Read full content and attachment metadata by IMAP UID.'),
    request: 'Path · uid; Query · accountId', response: '200 · { message }',
    examplePath: '/api/icloud/inbox/:uid?accountId=icloud_account_id',
  },
]

export const adminOperationEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/admin/mailbox-public-links', group: 'adminOperations', auth: 'superAdmin',
    title: l('查询邮箱取码链接状态', 'List mailbox code-link status'),
    description: l('主管理员按邮箱或所属用户搜索并筛选公开取码链接状态。', 'Let the owner search mailboxes or owners and filter public code-link status.'),
    request: 'Query · q?, status=all|enabled|disabled, limit?, cursor?', response: '200 · { mailboxes, page }',
    examplePath: '/api/admin/mailbox-public-links?status=all&limit=50',
  },
  {
    method: 'POST', path: '/api/admin/mailbox-public-links/bulk', group: 'adminOperations', auth: 'superAdmin',
    title: l('批量签发或撤销取码链接', 'Bulk issue or revoke code links'),
    description: l('主管理员为最多 100 个邮箱签发、重置或撤销公开取码链接。', 'Let the owner issue, reset, or revoke public code links for up to 100 mailboxes.'),
    request: 'JSON · action=issue|revoke, mailboxes[1..100]', response: '200 · { results }',
    exampleBody: { action: 'issue', mailboxes: ['a@example.com', 'b@example.com'] },
    notes: [l('签发响应中的 Token 明文只返回一次；审计日志不会保存 Token 或完整链接。', 'Plaintext tokens are returned only once when issued. Audit logs do not store tokens or full links.')],
  },
  {
    method: 'GET', path: '/api/admin/audit-logs', group: 'adminOperations', auth: 'admin',
    title: l('查询操作日志', 'Query audit logs'),
    description: l('按时间、类别和关键词查询脱敏审计记录并游标分页。', 'Query sanitized audit records by time, category, and keyword with cursor pagination.'),
    request: 'Query · days?, category?, q?, limit?, cursor?', response: '200 · { logs, page }',
    examplePath: '/api/admin/audit-logs?days=7&category=auth&limit=50',
  },
  {
    method: 'GET', path: '/api/admin/statistics', group: 'adminOperations', auth: 'admin',
    title: l('读取全站统计', 'Read site-wide statistics'),
    description: l('返回收件趋势、来源、发件人、平台用量和存储汇总。', 'Return receiving trends, sources, senders, platform usage, and storage summaries.'),
    request: 'Query · days=7|30|90?', response: '200 · { summary, daily, sourceDomains, topSenders, platform, storage }',
    examplePath: '/api/admin/statistics?days=30',
  },
  {
    method: 'GET', path: '/api/admin/deployment-check', group: 'adminOperations', auth: 'admin',
    title: l('执行部署自检', 'Run deployment checks'),
    description: l('检查 D1、R2、队列、Secret 和功能配置，不返回 Secret 明文。', 'Check D1, R2, queues, secrets, and feature configuration without returning secret values.'),
    request: 'No parameters', response: '200 · { groups, ready }',
  },
  {
    method: 'GET', path: '/api/admin/failed-messages', group: 'adminOperations', auth: 'admin',
    title: l('列出解析失败邮件', 'List failed messages'),
    description: l('返回仍可重试或需要清理的失败邮件摘要。', 'Return failed-message summaries that can be retried or cleaned up.'),
    request: 'No parameters', response: '200 · { total, messages }',
  },
  {
    method: 'POST', path: '/api/admin/failed-messages/:id/retry', group: 'adminOperations', auth: 'admin',
    title: l('重试失败邮件', 'Retry a failed message'),
    description: l('把指定失败邮件重新加入解析队列。', 'Requeue the selected failed message for parsing.'),
    request: 'Path · id', response: '200 · { ok: true }',
  },
  {
    method: 'GET', path: '/api/admin/mail-cleanup/preview', group: 'adminOperations', auth: 'admin',
    title: l('预估邮件清理', 'Preview mail cleanup'),
    description: l('按范围、类别和邮件年龄计算待清理数量、附件和空间。', 'Calculate messages, attachments, and bytes to clean by scope, category, and age.'),
    request: 'Query · scope=all|user|mailbox, scopeValue?, category, olderThanDays=1..3650', response: '200 · { filter, preview, batchLimit }',
    examplePath: '/api/admin/mail-cleanup/preview?scope=all&category=trash&olderThanDays=30',
  },
  {
    method: 'POST', path: '/api/admin/mail-cleanup', group: 'adminOperations', auth: 'admin',
    title: l('执行邮件清理', 'Run mail cleanup'),
    description: l('经数量复核后每批永久清理最多 50 封匹配邮件。', 'After count confirmation, permanently clean up to 50 matching messages per batch.'),
    request: 'JSON · scope, scopeValue?, category, olderThanDays, expectedCount, confirm=true', response: '200 · { deletedCount, deletedBytes, remainingCount }',
    exampleBody: { scope: 'all', scopeValue: '', category: 'trash', olderThanDays: 30, expectedCount: 12, confirm: true },
  },
  {
    method: 'GET', path: '/api/admin/messages', group: 'adminOperations', auth: 'superAdmin',
    title: l('查询全站邮件', 'Query site-wide messages'),
    description: l('主管理员按用户、邮箱、方向、文件夹、状态和时间筛选全站邮件。', 'Let the owner filter site-wide mail by user, mailbox, direction, folder, status, and age.'),
    request: 'Query · q?, user?, mailbox?, direction?, folder?, status?, days?, limit?, cursor?', response: '200 · { messages, page }',
    examplePath: '/api/admin/messages?folder=inbox&days=30&limit=30',
  },
  {
    method: 'PATCH', path: '/api/admin/messages/bulk', group: 'adminOperations', auth: 'superAdmin',
    title: l('批量管理全站邮件', 'Bulk-manage site-wide messages'),
    description: l('主管理员跨用户批量移入垃圾箱、恢复或永久删除邮件。', 'Let the owner move, restore, or permanently delete messages across users.'),
    request: 'JSON · ids[1..50], action=trash|restore|delete', response: '200 · { ok, updatedCount }',
    exampleBody: { ids: ['message_1', 'message_2'], action: 'trash' },
  },
  {
    method: 'GET', path: '/api/admin/messages/:messageId/attachments/:attachmentId', group: 'adminOperations', auth: 'superAdmin',
    title: l('读取任意用户附件', 'Read any user attachment'),
    description: l('主管理员下载或受限预览全站邮件附件，并写入审计日志。', 'Let the owner download or safely preview any attachment and write an audit event.'),
    request: 'Path · messageId, attachmentId; Query · preview=1?', response: '200 · attachment bytes',
    examplePath: '/api/admin/messages/:messageId/attachments/:attachmentId?preview=1', outputFile: 'attachment.bin',
  },
  {
    method: 'GET', path: '/api/admin/messages/:id/raw', group: 'adminOperations', auth: 'superAdmin',
    title: l('下载任意用户原始邮件', 'Download any raw message'),
    description: l('主管理员下载全站邮件的原始 EML，并记录访问审计。', 'Let the owner download any raw EML and record an access audit event.'),
    request: 'Path · id', response: '200 · message/rfc822', outputFile: 'message.eml',
  },
  {
    method: 'GET', path: '/api/admin/messages/:id', group: 'adminOperations', auth: 'superAdmin',
    title: l('读取任意用户邮件详情', 'Read any message details'),
    description: l('主管理员读取全站邮件正文、所属用户、线程和附件元数据。', 'Let the owner read any message body, owner, thread, and attachment metadata.'),
    request: 'Path · id', response: '200 · { message, thread }',
  },
]
